### ISSUE TITLE
Consider adopting the Open-Stand 5 Principles

### ISSUE THREAD

**Issue by mr-c** [ga4gh/product-process#1]
https://open-stand.org/about-us/principles/

![infographic](https://open-stand.org/wp-content/uploads/2014/08/OpenStand_5Principles_v4b.png)

**Comment by susanfairley** [comment]
Thanks for sharing this. I think these principles make sense and hope that we are broadly aligned with them already - but useful to keep in mind when reviewing our processes.

**Comment by vdauwera** [comment]
I support being explicit about this as well. Relatedly -- As familiar as I am with what "open source" means for software, I found myself researching what it means exactly for a standard to be open. I expect that might be the case of others in our community. I came across [this definition/ list of requirements](https://opensource.org/osr) which is also helpful in my opinion, for the avoidance of doubt.

**Comment by andrewyatz** [comment]
After speaking around [GA4GH's original 2013 white paper](https://www.ga4gh.org/wp-content/uploads/White-Paper-June-3-final.pdf) did reference OpenStand as a group to be aware of and to learn from other standards organisations. [OpenStand's web presence](https://open-stand.org/about-us/) is now archived. So perhaps what's been done is more than enough?

**Comment by mr-c** [comment]
@andrewyatz I think it would be nice to make the goal explicit by including a link; we can come back later and self-audit as policies and practices change

**Comment by susanfairley** [comment]
Thanks for the further comments here.

Looking at this material, it seems it is no coincidence that GA4GH is well aligned with OpenStand, as it clearly informed the thinking at the time of the 2013 White Paper.

I'm not aware that GA4GH has ever outright formally committed to OpenStand and, if we were to do so, that would likely be a step that would need some combination of Steering Committee and Executive Committee approval. It feels like a decision that we'd need to take as an organisation - so beyond the scope of this document.

However, I do like both of these pieces of text and take on board @vdauwera's point about providing clarity on what is meant by 'open standards'. I'd be interested in including links as background information for those unfamiliar with the idea of open standards, with wording that the links are there for context and background information on general usage of the term 'open standards'.

Happy to hear thoughts.

**Comment by jkbonfield** [comment]
I think it's got a lot of synergy with how we work, but by itself it's not sufficient to describe the principles of GA4GH standards so we'll need our own documentation anyway.

For example "Openness. Standards processes are open to all interested and informed parties" doesn't say for-free.  ISO typically charge for access to their specifications (unlike IETF from what I understand), but they may well describe it as a fair and open distribution policy as everyone has equal access and no one is denied the ability to purchase a copy of the specification.   This is emphasised at the end by their comment about the possibility of using FRAND licensing.  We ne our own licensing and IP guidance, and emphasis that all our standards are royalty free.

Also under "Due Process": "Processes for periodic standards review and updating are well defined".  Open-Stand doesn't define what those processes are, only state that they re well defined.  So again we'd need to define them anyway, and indeed already are doing so.

Clearly GA4GH can use open-stand definitions as a basis, but if so we'd want to expand upon them.  So we either use them for ideas and rewrite as our own set of principles, or we build on top of them.  Either way I see no problem with stating that our principles are compliant and/or compatible with the Open-Stand ones.  (Assuming that they are - they certainly look reasonable to me.)

**Comment by susanfairley** [comment]
Thanks @jkbonfield. This is useful feedback. Noting that work on, for instance, the IP policy, will continue and that the intention is that this document will be supported by that and other policies, which should provide further detail.

**Comment by susanfairley** [comment]
Thanks for this @larrybabb. Related to your points about communicating with potential adopters about the extent of adoption, I'd like to flag the planning for adoption issue #9 .

**Comment by mr-c** [comment]
> I've always struggled with the ease at which we (ga4gh collectively) uses the term "standard" . While it is clear that products like VCF are "standards", I think other products within GA4GH are more or less "proposed standards" or "evolving standards". I think it is really important for ga4gh to offer more detail around this topic of "open standards" or just "standards" in themselves so those exploring the products being developed by ga4gh understand the actual level of "standardization" that these products can truly claim.

It may help if we think about "standards" as agreement that a specific name means a specific thing. So there isn't "THE standard for wireless communication", but many WiFi standards; when talk about the "802.11n WiFi standard" we aren't saying there are other standards available.

To me, standards are a marketplace of well-named and well-defined specifications. Stakeholders should feel free to choose any relevant standards, or none at all.

If somethings has a name and a well defined specification; it could be called a standard. It might not get adopted; it might have other problems, but it is a standard. 

It is tricky that in (American?) English we use the word "standard" to also mean "the most popular" or "the correct way".

**Comment by jkbonfield** [comment]
Some other standards bodies have different classes of standard, such as [ISO ](https://www.iso.org/stages-and-resources-for-standards-development.html) with work-in-progress, draft standard (DIS), final draft standard (FDIS), etc   Other terms are employed elsewhere.  However none of these are particularly related to the level of adoption.  Rather they are labels to show the state and progress being made prior to the final release.

Some final accepted standards may just wither and not get adopted, maybe because they're too complicated or simply because the world has moved on and they weren't timely enough.  I think we could get bogged down if we tried to rationalise the levels of adoption.  We just have to work on the "build it and they will come" principle / hope, and provided we have gone through the process of demonstrating need and validation that it is fit for purpose I think that is sufficient.  This is the purpose of the review committees.

I agree though that until we have had final sign off, we could perhaps be clearer on our terminology, labelling things as "draft standards" for example.  I think some working groups already do this.

**Comment by larrybabb** [comment]
@mr-c and @jkbonfield thank you both for the explanations above. That definitely helps allay my concerns over the term "standards" as I was definitely thinking of it more in the strict sense of "the correct or most popular way".  

In terms of using the term "standards" within the GKS workstream, I will ease up on my concern, but I would also push to find a way to be much more transparent on the level of adoption and acceptance that is or has occurred with a given version of the "standard specifications".  IMO gaining adoption of a new "standard" like VRS or VA or other GKS efforts is really about showing folks the benefits of it in real data, systems and tooling. Without any meaningful adoption like "reference" libraries, schemas, tools and datasets, it is really not a finalized product or one that most if any will simply adopt. It certainly would take a long time to become "the popular or correct way".

I would also like to add, that as GKS and other workstreams create new standards or products we acknowledge that the first version (or two) of these are likely to change in a way that is not backward compatible. It is not until several independent groups adopt the product and provide the feedback to refine it such that it is proven to "fit" the needs of the community it is intended for does it really become a viable "standard".  GKS is working very hard to innovate ("implement" and "refine") with several driver projects and a large commercial vendor to demonstrate that the tools and specs we are developing are worth investing in by the early adopters and early majority within the community.
