### ISSUE TITLE
conflict with GA4GH policies for outside products

### ISSUE THREAD

**Issue by yannjoly** [ga4gh/product-process#15]
1.	For products that originated outside of GA4GH (e.g. BED), check if there is any potential conflict with GA4GH policies, for example, relating to IP. Existing IP, or other factors, may prevent GA4GH from being able to adopt a product.
I am not sure flagging IP specifically here is necessary. It could give a wrong impression that this is the main (or only consideration) relevant under 1. 
1 i.  replace ‘this’ by ‘products that originated outside of GA4GH’
iii. I’m not sure the IP group comprise a sufficient expertise to oversee all potential conflicts which maybe completely outside of the IP domain.

**Comment by michaelmhoffman** [comment]
What other potential conflicts do you envision?

**Comment by yannjoly** [comment]
The most obvious example would be a clear conflict with a core element or foundational principle of the Framework for Responsible Sharing of Genomic and Health Related Data  https://www.ga4gh.org/genomic-data-toolkit/regulatory-ethics-toolkit/framework-for-responsible-sharing-of-genomic-and-health-related-data/

**Comment by susanfairley** [comment]
@yannjoly - noting that the IP checklist would be insufficient. Also happy to switch "This" in 1. i to the suggested wording.

Returning to 1. iii: I think a checklist from the IP group could be useful but agree that this wording may imply that that is sufficient, which I don't think it is. Maybe the wording could be revised to:
_1. iii. Criteria: is there anything in the history of the product that would make it incompatible with GA4GH policies? This could be the IP policy, ethical frameworks or some other consideration. (Checklists can be developed by relevant groups to aid review but those making the decision should be cognisant that checklists cannot be exhaustive for all circumstances and that active consideration of issues beyond any checklists is required)_

Thoughts welcome.
