### ISSUE TITLE
Process related

### ISSUE THREAD

**Issue by RegganThomas** [ga4gh/product-process#20]
Principle no 2 - Should we define how broad consultation and consensus are obtained for product development? or make a reference to section 12 of specific notes?
Principle no 7 - Would a hyperlink to the code of conduct be useful?
Principle no 8 - Should we add any links to the best practices?
Principle no 10 - Documents generated during the process should only be saved on a GA4GH shared drive ?
Principle no 11 - Should we track those changes in the revision history of the product development document?

Specific notes:
1) Is there a checklist or team that should be consulted to ensure that the product outside GA4GH does not have any conflicts?

6)
a) Should the team provide any documentation to state that the product is needed and fulfil a need that is not met by any existing effort? 
e)
    a) Hyperlink to be added for communication teams?
    c) Hyper link to be added for Regulatory-Ethics and Security ?
     
f) Study group output needs to be communicated to the secretariat or be presented in any forum?

14) V) - Should the team develop acceptance criteria for the use cases? so that the review process mentioned in point no. 15 can be monitored?
22) 
I) a) If the team has used any "existing landscape" as mentioned in 6-e-d, that should be provided as output during the final presentation to SC ?

I) a) As an output to be presented during the final SC meeting, the team needs to obtain a report from the TASC team to substantiate that the product interoperates with existing products (from GA4GH or elsewhere) ?

I)a) Do we need to provide any evidence during the final SC meeting that the product answered the problem statement?

Process flow diagram :
Between the connection point 4 - 5 : Should we mention that the user should work with the secretariat if they are interested in continuing?
General :
1) Is there a timeframe that needs to be followed for each phase of product development?
2) Do we need to think about the FAQ section for the product development process?

**Comment by susanfairley** [comment]
Thanks for these comments. There are, I think, a number of different issues being raised here.

1. For working practices, that is probably better addressed in the Best Practices document. There should be some freedom for people to decide how they want to achieve goals. We can recommend options in Best Practices and ask that people follow them or do something else and demonstrate that their option is as good. Some of the specifics will depend on the context for a given product. I think this document should focus on the logical flow for product development, with working practices elsewhere.
2. Some of the companion documents are in progress, hence no links at time of writing but they would be a good addition.
3. Document storage and revision tracking are essential but, again, probably better addressed in Best Practices.
4. Checklists can be useful but possible issues beyond those on the checklist need active consideration - I'd be sceptical that an early draft of a checklist would capture everything.  It needs people actively reviewing, engaging and thinking - ticking boxes isn't good enough.
5. The products are diverse, there needs to be adaptability to recognise that.
6. The decision making criteria should be referred to when decisions on evidence to be presented at any stage are being made.
7. Interoperability is assessed by the PRC, using their knowledge of the field, as to what is appropriate. TASC play a role, as needed, during development but it's the PRC who have responsibility for review. I'd have concerns about adding to TASC's workload - they already deal with detail during development.
8. Output of landscape analysis is presented to the PRC (10. i. a (10.i lists the study group outputs for review)) and then the SC. The idea is to demonstrate convincingly that a landscape analysis has taken place, thereby offering encouragement that the standard is in fact needed.
9. Acceptance criteria being added is an interesting idea
10. The *final* SC looks at process, not content. The earlier SC reviews content. Criteria include 17. iv. b. a - so yes, evidence of meeting the problem statement is very much necessary.
11. It should be clear that Secretariat support the whole process, we could add another statement at the top to clarify.
12. No timeframe beyond those specified for the Study Group.

I'm not sure if I've succeeded in addressing all of the points you raised.

For me, these are valuable points but some of them I think are better handled in Best Practices.

To take forward to action in this document, I'm interested in considering:
1. Acceptance criteria for use cases
2. Clarifying that Secretariat support the whole process
3. Adding supporting links where possible

Happy to hear any further thoughts on this.
