### ISSUE TITLE
Timeline of new REWS-DSWS Questionnaire

### ISSUE THREAD

**Issue by lindsmith** [ga4gh/product-process#22]
Specific Notes 17i

My understanding of the new REWS-DSWS form is that that the questionnaire is completed at the beginning/proposal stage, and then there is a much shorter review/reflection at the approval stage. Suggest moving the "complete the questionnaire" phrase to 6.i.e.c where it describes a first consultation with REWS and DSWS.

**Comment by susanfairley** [comment]
Thanks for this. Similar points raised elsewhere. Discussion and clarification (hopefully) on #27
