### ISSUE TITLE
Establish Study Group 

### ISSUE THREAD

**Issue by MailiRaven** [ga4gh/product-process#26]
Here, there is reference to REWS and Security consultation. I would suggest this changes to 'proposal of product goes through rews and security review'

**Comment by MailiRaven** [comment]
This could be reflected under '6'

**Comment by susanfairley** [comment]
There may be confusion on my part but there isn't a product proposal at point 6 - rather the Study Group is forming to work on a problem definition. Happy to consider changing the wording but I'm not sure that 'proposal of product' is appropriate. Any clarification welcome. Thanks.
