### ISSUE TITLE
Two SC votes?

### ISSUE THREAD

**Issue by ajhpage** [ga4gh/product-process#29]
> Point 20: Steering Committee subset/delegates offline ballot on content
> Point 22: Final presentation to Steering Committee for approval that the product development has followed our process

Are we asking SC to vote on content and then two weeks later to cast a second vote on whether or not the process was followed? Is it possible to roll these into one vote? 

- Do you approve of the content? yes/no
- If yes, do you also approve that the process was followed? yes/no

**Comment by susanfairley** [comment]
On content votes, in the current draft, SC members can nominate others to vote on their behalf. Proxies don't feature in the final process vote, so these could be two different sets of people voting.
